palabras = ["aire", "ojos","uña", "boca", "nariz", "cara", "cejas",
"sonrisa","piel", "joven", "viejo", "anteojos", "alto", "bajo", 
"pequeño", "gordo", "delgado","bella", "azul", "verde", "negro",
"sombrero", "guantes", "corbata", "gemelos", "paraguas", "plata",
"oro", "perla", "diamante", "esmeralda", "anillo", "pulsera", "rico",
"reloj", "elegante", "sencillo", "chaqueta", "traje", "camisa", "pobre",
"zapatos", "pelo", "maquillaje", "peine", "dedo", "hueso", "calor",
"ambulancia", "enfermera","araña", "farmacia", "vitaminas", "pastillas",
"dentista", "ciego", "correr", "caminar", "regresar", "saltar","tamaño",
"fin", "cerrar", "nombre", "mujer", "hombre", "soltero", "novio",
"nacer", "vivir", "edad", "anciana", "trabajar", "cobrar", "azafata",
"artista", "panadero", "carpintero", "cocinero", "maestro", "bombero",
"juez", "modelo", "monje", "pintor", "piloto", "secretaria", "taxista",
"escritor", "jefe", "aprendiz", "jubilado","sueño","cumpleaños"," empleo", 
"industria","piña","montaña", "muñeca", "año", "puño", "niña", "gruñon", 
"taller", "tienda", "vacaciones", "sueldo", "impuesto", "huelga","huella",
"leña", "pañuelo","baño", "cabaña","engaño", "extraño", "dañar","rebaño",
"obedecer", "locura", "humor", "inteligencia", "orgullo", "timidez",
"valiente", "aburrido", "loco", "divertido", "bueno", "feliz", "amable",
"pobre", "serio", "extraño", "gritar", "llorar", "suspirar", "preocupado",
"risa", "amor", " suerte", "enamorado", "ver", "apagar", "luz", "color",
"lupa", "microscopio", "claro", "cantar", "silvar", "voz", "eco", "trueno",
"altavoz", "radio", "auricular", "liso", "comer", "dulce", "salado","mañana",
"albañil", "añadidura", "telaraña","bañera", "meñique", "pañuelo","año",
"perfume", "despertarse", "vestirse", "desayunar", "leer", "dormirse", 
"toalla", "almuerzo", "sopa", "agua", "leche", "jugo", "sal", "pimienta",
"vinagre", "camarones", "tortilla", "espagueti", "sopa", "helado", "chocolate",
"galletas", "bombones", "limpiar", "cortar", "hervir", "planchar", "horno", 
"abrelatas", "vajilla", "vaso", "cafetera","comprar", "gastar", "vender", "barato"]